name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: coeval
          MYSQL_ROOT_HOST: '%'  # 允许从任何主机连接
        ports:
          - 3306:3306
        # 使用 command 来设置 MySQL 配置
        command: --default-authentication-plugin=mysql_native_password

    env:
      MYSQL_HOST: localhost
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: coeval

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        pip install -r test/requirements.txt
    
    - name: Wait for MySQL
      run: |
        for i in {1..30}; do
          if mysql -h localhost -P 3306 -u root -proot -e "SELECT 1" > /dev/null 2>&1; then
            echo "MySQL is ready!"
            break
          fi
          echo "Waiting for MySQL... ($i/30)"
          sleep 2
          if [ $i -eq 30 ]; then
            echo "MySQL failed to start"
            exit 1
          fi
        done
    
    - name: Initialize database
      run: |
        cd database
        python init_manual.py
    
    - name: Start backend server
      run: |
        cd backend
        python run.py &
        sleep 5  # 给服务器一些启动时间
    
    - name: Run tests
      run: |
        cd test
        pytest -v