name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: coeval
          MYSQL_ROOT_HOST: '%'  # 允许从任何主机连接
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        pip install -r test/requirements.txt
    
    - name: Configure MySQL
      run: |
        # 等待 MySQL 启动
        sleep 10
        # 配置 MySQL 允许任何主机连接
        mysql -h localhost -P 3306 -u root -proot -e "ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'root'; FLUSH PRIVILEGES;"
        mysql -h localhost -P 3306 -u root -proot -e "CREATE DATABASE IF NOT EXISTS coeval;"
    
    - name: Initialize database
      run: |
        cd database
        # 查看初始化脚本的内容
        head -n 20 init_manual.py
        # 修改数据库连接配置
        sed -i "s/DB_CONFIG = {/DB_CONFIG = {\n    'host': 'localhost',\n    'user': 'root',\n    'password': 'root',\n    'database': 'coeval',/" init_manual.py
        python init_manual.py
    
    - name: Start backend server
      run: |
        cd backend
        # 修改后端数据库配置
        grep -r "mysql.connector.connect" app/
        # 修改后端数据库连接参数
        sed -i "s/connection = mysql.connector.connect(/connection = mysql.connector.connect(host='localhost', user='root', password='root', database='coeval', /" app/utils/db.py
        python run.py &
        sleep 5  # 给服务器一些启动时间
    
    - name: Run tests
      run: |
        cd test
        pytest -v