name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        pip install -r test/requirements.txt
    
    - name: Set up MySQL
      run: |
        sudo systemctl start mysql
        sudo mysql -e "CREATE DATABASE coeval;"
        sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';"
        sudo mysql -e "FLUSH PRIVILEGES;"
    
    - name: Initialize database
      run: |
        cd database
        python init_manual.py
    
    - name: Start backend server
      run: |
        cd backend
        python run.py &
        sleep 5
    
    - name: Run tests
      run: |
        cd test
        pytest -v 